//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emoda.PekiYaBen.Web.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ProfilePhoto { get; set; }
        public string PhoneNumber { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string EducationInfo { get; set; }
        public string CoachingInfo { get; set; }
        public string CertificateInfo { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<bool> ShowMainPage { get; set; }
        public int Status { get; set; }
    }
}
