//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PekiYaBen.WebSite.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] ProfilePhoto { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> OccupationStatus { get; set; }
        public string City { get; set; }
        public bool CommunicationPermission { get; set; }
        public Nullable<System.DateTime> CommunicationPermissionUpdate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string LastLoginIp { get; set; }
        public Nullable<int> SocialMedia { get; set; }
        public string SocialMediaId { get; set; }
        public string SocialMediaToken { get; set; }
        public string Token { get; set; }
        public string FCMToken { get; set; }
        public bool Status { get; set; }
        public System.DateTime RegisterDate { get; set; }
    }
}
