//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PekiYaBen.WebSite.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachCalendarUser
    {
        public int Id { get; set; }
        public int CoachCalendarId { get; set; }
        public Nullable<int> AppUserId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string InterviewType { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
