//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PekiYaBen.WebSite.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachCalendar
    {
        public int Id { get; set; }
        public int CoachId { get; set; }
        public System.DateTime AvailableDate { get; set; }
        public string InterviewType { get; set; }
        public Nullable<int> ParticipantLimit { get; set; }
        public Nullable<bool> CoachIsFull { get; set; }
        public int Status { get; set; }
    }
}
