//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PekiYaBen.WebSite.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> CoachId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Detail { get; set; }
        public int Type { get; set; }
        public string Image { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Status { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public string ProductIds { get; set; }
    }
}
