//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PekiYaBen.WebSite.Models.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PekiYaBenDBEntities : DbContext
    {
        public PekiYaBenDBEntities()
            : base("name=PekiYaBenDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ContentCategory> ContentCategories { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<InvoiceInfo> InvoiceInfoes { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<CoachCalendar> CoachCalendars { get; set; }
        public virtual DbSet<CoachCalendarUser> CoachCalendarUsers { get; set; }
        public virtual DbSet<GeneralParameter> GeneralParameters { get; set; }
    }
}
