//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PekiYaBen.WebSite.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public int Type { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string File { get; set; }
        public string ContentImage { get; set; }
        public string ContentDescription { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public int Status { get; set; }
        public Nullable<bool> ShowMainPage { get; set; }
    }
}
